db:
  mode: sqlite # Supports: mysql pgsql sqlite
  db_name: test.db
  host: 127.0.0.1
  port: 3306
  user: root
  password: root

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 1

gin:
  ip: 127.0.0.1
  port: 8080
  mode: release # debug release test

jwt:
  expire: 24
  issuer: fast-gin
  secret_key: my-secret-key

upload:
  size: 2 # MB
  dir: images

site:
  login:
    captcha: true
  